config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'homes#top', as: 'top'
    get 'about', to: 'homes#about', as: 'about'
    get 'data', to: 'analyses#data', as: 'data'
    get 'rank', to: 'analyses#rank', as: 'rank'
    get 'searches', to: 'searches#search', as: 'search'
    get 'bookmarks', to: 'bookmarks#index', as: 'bookmark'

    resources :users, only: %i[show edit update]
    get 'users/:user_id/withdraw', to: 'users#withdraw', as: 'withdraw'
    patch 'users/:user_id/switch', to: 'users#switch', as: 'switch'
    resources :posts, only: %i[index show edit create update destroy] do
      resource :likes, only: %i[index create destroy]
      resources :post_comments, only: %i[create update destroy]
      collection do
        get :cities_select
      end
    end
    resources :albums, only: %i[index show edit create update destroy] do
      resource :bookmarks, only: %i[create destroy]
    end

    resources :prefectures, only: %i[index]
    resources :genres, only: %i[index create update destroy]
    get 'budget', to: 'genres#budget', as: 'budget'
    get 'age', to: 'genres#age', as: 'age'
    get 'nation', to: 'genres#nation', as: 'nation'
    resources :events
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  admin                  :boolean          default(FALSE), not null
#  age                    :integer          not null
#  country_code           :string(255)      not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  name                   :string(255)      not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  state_code             :string(255)
#  withdrawal_flag        :boolean          default(FALSE), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  image_id               :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy, inverse_of: :visitor
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy, inverse_of: :visited

  attachment :image

  validates :name, presence: true, length: { in: 1..50 }
  validates :age, presence: true
  validates :country_code, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true # format: { with: VALID_EMAIL_REGEX, allow_blank: true }
  validates :withdrawal_flag, inclusion: { in: [true, false] }
  validates :admin, inclusion: { in: [true, false] }

  scope :age_20, -> { where("users.age > ?', '1..20'") }
  scope :age_30, -> { where("users.age > ?', '20..30'") }
  scope :age_40, -> { where("users.age > ?', '30..40'") }
  scope :age_50, -> { where("users.age > ?', '40..50'") }
  scope :age_60, -> { where("users.age > ?', '50..60'") }
  scope :age_70, -> { where("users.age > ?', '60..70'") }
  scope :age_80, -> { where("users.age > ?', '70..80'") }

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protect_from_forgery
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # new_user_registration_path
  # def new
  #   super
  # end

  # POST /resource
  # user_registration_path
  def create
    super
    # Empty Recorde Create (album, event)
    return unless @user.save

    event = @user.events.new(user_id: @user.id, genre_id: 1)
    if event.save
      album = @user.albums.new(user_id: @user.id, genre_id: 1, title: '', post_quantity: 0)
      album.save
    end
    flash[:notice] = t('users.flash.s_notice')
  end

  # GET /resource/edit
  # edit_user_registration_path
  # def edit
  #   super
  # end

  # PUT /resource
  # user_registration_path
  # def update
  #   super
  # end

  # DELETE /resource
  # user_registration_path
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  protect_from_forgery
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: %i[show edit withdraw switch update]

  include UserStatus
  include Page

  # GET /users/:id
  # user_path
  def show
    pg_p = params[:post]
    pg_a = params[:album]
    @theuser = current_user
    @posts_pg = type_page_8(@theuser.posts, pg_p)
    @albums_pg = type_page_6(@theuser.albums, pg_a)
    notifications = page_5(current_user.passive_notifications)
    notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
    @notice_by_others = notifications.where.not(visitor_id: current_user.id)
    @event = Event.new
    @events = current_user.events.order(created_at: 'DESC')
    from = Time.current
    to = Time.current.since(3.days)
    @events_3days = current_user.events.where(start: from...to)
    # Count User Got
    @posts = @theuser.posts
    @albums = @theuser.albums
    @get_likes = get_post(@posts, Like)
    @get_comments = get_post(@posts, PostComment)
    @get_bookmarks = get_album(@albums, Bookmark)
    # Count User Gave
    @give_likes = give_obj(Like, @theuser)
    @give_comments = give_obj(PostComment, @theuser)
    @give_bookmarks = give_obj(Bookmark, @theuser)
    respond_to do |format|
      format.html
      format.json { render json: @events }
    end
  end

  # GET /users/:id/edit
  # edit_user_path
  def edit
    @theuser = current_user
  end

  # GET /users/:user_id/withdraw
  # withdraw_path
  def withdraw
    @theuser = current_user
  end

  # PATCH /users/:user_id/switch
  # switch_path
  def switch
    @theuser = current_user
    if @theuser.update(withdrawal_flag: true)
      redirect_to top_path
    else
      render :withdraw
    end
  end

  # PATCH /users/:id
  # user_path
  def update
    @theuser = current_user
    if @theuser.update(user_params)
      redirect_to user_path(@theuser.id), notice: t('users.flash.u_notice')
    else
      flash.now[:alert] = t('users.flash.u_alert')
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :image, :age, :country_code)
  end

  def correct_user
    if params[:user_id].present?
      user = User.find(params[:user_id])
      redirect_to user_path(current_user), alert: t('app.flash.no_access') if user.id != current_user.id
    elsif params[:id].present?
      if params[:id] != 'sign_out' || params[:id] != 'sign_in'
        user = User.find(params[:id])
        redirect_to user_path(current_user), alert: t('app.flash.no_access') if user.id != current_user.id
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.slim
.user-main__box
  .row
    .col-xs-12
      .col-xs-6
        = render 'layouts/error_message', model: @theuser
  .row
    .col-xs-6
      .user-main__new-form
        = form_with(model: @theuser , url: user_path, method: :patch, local: true) do |f|
          .user-main__image
            .form-window.row
              = f.label t('users.common.image'), class:"user-main__color"
              br
                #img_field onClick="$('#file').click()"
                  - if @theuser.image.present?
                    = attachment_image_tag @theuser, :image, fallback:"img/no_photo.png", class:"field", size:"80x80"
                  - else
                    i.fas.fa-image
                    i.fas.fa-file-upload.add
              = f.attachment_field :image, style:"display:none;", id:"file"
              .form-window.row
                = f.label t('users.common.name'), class:'user-main__color'
                br
                = f.text_field :name
              .form-window.row
                = f.label t('users.common.age'), class:'user-main__color'
                br
                = f.select :age, options_for_select(1..100, selected: @theuser.age), autofocus: true, autocomplete: "age"
              .form-window.row
                = f.label t('users.common.nation'), class:'user-main__color'
                br
                = f.country_select :country_code, autofocus: true, autocomplete: "country", prompt: "Please select a country"
              .form-window.row
                = f.label t('users.common.mail'), class:'user-main__color'
                br
                = f.email_field :email, autofocus: true, autocomplete: "email"
              .form-submit.row
                = f.submit t('users.common.submit'), class: "btn btn-primary btn-md pull-left update-btn"

app/views/users/_show_form.html.slim
.event-form
  .event-form__title
    h2
      = t('users.show.new_form')
  .event-form__form
    = form_with(model: event, url: events_path, method: :post, local: true) do |f|
      .form-window.row
        = f.label t('users.show.f_title')
        br
        = f.text_field :title
      .form-window.row
        =f.label t('users.show.f_description')
        br
        = f.text_area :body
      .form-window.row
        = f.label t('users.show.f_genre')
        br
        = f.collection_select :genre_id, Genre.all, :id, :name, prompt: "Please select"
      .action.row
        = f.submit t('users.show.f_submit'), class:"btn btn-primary"

app/views/users/_show_setting.html.slim
.mypage-setting
  .col-xs-4
    .mypage-setting__part
      .mypage-setting__icon
        = link_to edit_user_path(user), method: :get do
          i.fas.fa-cogs name="edit_user"
      .mypage-setting__text
        = link_to edit_user_path(user), method: :get do
          h4
            = t('users.show.edit_info')
  .col-xs-4
    .mypage-setting__part
      .mypage-setting__icon
        = link_to albums_path, method: :get do
          i.fas.fa-book name="create_album"
      .mypage-setting__text
        = link_to albums_path, method: :get do
          h4
            = t('users.show.create_album')
  .col-xs-4
    .mypage-setting__part
      .mypage-setting__icon
        = link_to posts_path, method: :get, value:"create_post" do
          i.fas.fa-file-signature value="create_post"
        /= link_to posts_path, method: :get, value:"create_post" do
      .mypage-setting__text
        = link_to posts_path, method: :get, value:"create_post" do
          h4
            = t('users.show.create_post')

app/views/users/_show_status.html.slim
.mypage-status
  .col-xs-12.mypage-status__got
    = t('users.show.got')
    .mypage-status__icon
      .col-xs-12
        .col-xs-4
          .mypage-like__icon--like
            span.glyphicon.glyphicon-thumbs-up style="font-size:20px;"
        .col-xs-4
          .mypage-status__icon--comment
            span.glyphicon.glyphicon-comment style="font-size:20px;"
        .col-xs-4
          .mypage-status__icon--bookmark
            span.glyphicon.glyphicon-bookmark style="font-size:20px;"
    .mypage-status__count
      .col-xs-12
        .col-xs-4
          .mypage-status__like
            .mypage-like__count--like
              - if get_likes.nil?
                | 0
              - else
                = get_likes.count
        .col-xs-4
            .mypage-status__count--comment
              - if get_comments.nil?
                | 0
              - else
                = get_comments.count
        .col-xs-4
            .mypage-status__count--bookmark
              - if get_bookmarks.nil?
                | 0
              - else
                = get_bookmarks.count
  .col-xs-12.mypage-status__gave
    = t('users.show.gave')
    .mypage-status__icon
      .col-xs-12
        .col-xs-4
          .mypage-like__icon--like
            span.glyphicon.glyphicon-thumbs-up style="font-size:20px;"
        .col-xs-4
          .mypage-status__icon--comment
            span.glyphicon.glyphicon-comment style="font-size:20px;"
        .col-xs-4
          .mypage-status__icon--bookmark
            span.glyphicon.glyphicon-bookmark style="font-size:20px;"
    .mypage-status__count
      .col-xs-12
        .col-xs-4
          .mypage-status__like
            .mypage-like__count--like
              - if give_likes.nil?
                | 0
              - else
                = give_likes.count
        .col-xs-4
            .mypage-status__count--comment
              - if give_comments.nil?
                | 0
              - else
                = give_comments.count
        .col-xs-4
          = link_to bookmark_path
            .mypage-status__count--bookmark
              - if give_bookmarks.nil?
                | 0
              - else
                = give_bookmarks.count

app/views/users/edit.html.slim
.user-edit-page-bg
  .col-xs-4
    .user-sidebar
      .top-wrapper
        h1
          = t('users.edit.pagetitle')
        .row
          .user-sidebar__image
            = attachment_image_tag @theuser, :image, fallback:"img/no_image.png", class:"field user-sidebar__img", size:"200x200"
        .row
          .user-sidebar__detail
            table.table.table-bordered
              thead
                tr
                  th = t('users.common.name')
                  td.user-sidebar__title
                    = @theuser.name
                tr
                  th = t('users.common.age')
                  td.user-sidebar__title
                    = @theuser.age
                tr
                  th = t('users.common.nation')
                  td.user-sidebar__title
                    = @theuser.country_code
                tr
                  th = t('users.common.email')
                  td.user-sidebar__title
                    = @theuser.email
                tr
                  th = t('users.common.created')
                  td.user-sidebar__title
                    - if params[:locale] == 'ja'
                      = ja_time_fmt @theuser.created_at
                    - else
                      = time_fmt @theuser.created_at
        .row
          .col-xs-8
            .col-xs-12
              .post-main__top-btn
                = link_to user_path(@theuser), method: :get  do
                  span.btn.btn-success.btn-lg.col-xs-12.btn-icon-color
                    = t('users.edit.back')
            .col-xs-12
              .post-main__top-btn
                = link_to withdraw_path(current_user), method: :get  do
                  span.btn.btn-danger.btn-lg.col-xs-12.btn-icon-color
                    = t('users.edit.withdraw_btn')

  .col-xs-8.user-main__detail
    = render 'edit_form', theuser: @theuser

app/views/users/show.html.slim
.user-page-bg
  .top-wrapper
    .row
      .col-xs-12.text-center
        - if current_user.admin?
          h4
            | 管理者ページ

        - else
          h1.user-show__font-white
            = t('users.show.pagetitle')
    .row
      .col-xs-12.user-detail-box
        .col-xs-7
          .col-xs-6
            .col-xs-12
              = attachment_image_tag @theuser, :image, fallback:'img/no_image.png', class:'user-detail-box__img'
            .col-xs-12.user-detail-box__item
              .col-xs-4
                = t('users.common.name')
              .col-xs-8
                = @theuser.name
            .col-xs-12.user-detail-box__item
              .col-xs-4
                = t('users.common.mail')
              .col-xs-8
                = @theuser.email
            .col-xs-12.user-detail-box__item
              .col-xs-4
                = t('users.common.age')
              .col-xs-8
                = @theuser.age
            .col-xs-12.user-detail-box__item
              .col-xs-4
                = t('users.common.nation')
              .col-xs-8
                = @theuser.country_code
            .col-xs-12.user-detail-box__item
              .col-xs-4
                = t('users.common.created')
              .col-xs-8
                - if params[:locale] == 'ja'
                  = ja_time_fmt @theuser.created_at
                - else
                  = time_fmt @theuser.created_at
            .col-xs-12
          .col-xs-6
            = render 'users/show_status', get_likes: @get_likes, get_comments: @get_comments, get_bookmarks: @get_bookmarks, give_likes: @give_likes, give_comments: @give_comments, give_bookmarks: @give_bookmarks
          .col-xs-12
            = render 'users/show_setting', user: current_user
        .col-xs-5
          .user-cal-history
            .col-xs-12
              .user-cal-history__title
                = t('users.show.user_notice')
            .col-xs-12
              .user-cal-history__items
                - if @notice_by_others.exists?
                  = render @notice_by_others
                  = paginate @notice_by_others
                - else
                  = t('users.show.no_notice')

    .row
      .calendar-box
        .col-xs-7
          .calendar-box__cal
            #calendar
              div id='inputForm'
                = render 'events/form', event: @event
              div id='inputEditForm'
                = render 'events/edit_form', events: @events

        .col-xs-5
          .user-cal-history
            .col-xs-12
              .user-cal-history__title
                = t('users.show.3days_event')
            .col-xs-12
              .user-cal-history__items
                - if @events_3days.exists?
                  - @events_3days.each do |event|
                    .col-xs-12
                      |  -  
                      = event.title
                      | (
                      = event.genre.name
                      | ) :  
                      = event.body
                - else
                  .col-xs-12
                    = t('users.show.no_notice')
            .col-xs-12
              .user-cal-history__title
                = t('users.show.event_notice')
            .col-xs-12
              .user-cal-history__items
                - if @events.exists?
                  - @events.each.with_index do |event, i|
                    - if i < 6
                      .col-xs-12
                        .user-cal-history__item
                          - if params[:locale] == 'ja'
                            = ja_hour_fmt event.created_at
                            |  
                            = t('users.show.notice_text_1')
                            |  
                            = event.title
                            |  
                            = t('users.show.notice_text_2')
                          - else
                            = hour_fmt event.created_at
                            |  
                            = t('users.show.notice_text_1')
                            |  
                            = event.title
                - else
                  .col-xs-12
                    .user-cal-history__item
                      = t('users.show.no_notice')

    .row
      .tab-menu
        ul.nav.nav-tabs.text-center role="tablist"
          li.active role="presentation"
            a.text-cetner aria-control="tab_a" data-toggle="tab" href="#tab_a" role="tab"
              = t('activerecord.models.post')
          li role="presentation"
            a.text-cetner aria-control="tab_b" data-toggle="tab" href="#tab_b" role="tab"
              = t('activerecord.models.album')
    .row
      .tab-content
        .tab-pane.active id="tab_a" role="tabpanel"
          .mypage-post-list
            .col-xs-12.text-center
              .mypage-post-list__title
                - if @posts_pg.nil?
                    = t('app.common.no_post')
                - else
                    = t('users.show.subtitle_p')
              .col-xs-12
                = render @posts_pg
                .text-center
                  = paginate @posts_pg, :param_name => 'post'

        .tab-pane id="tab_b" role="tabpanel"
          .mypage-post-list
            .col-xs-12.text-center
              .mypage-post-list__title
                - if @albums_pg.nil?
                    = t('app.common.no_album')
                - else
                    = t('users.show.subtitle_a')
              .col-xs-12
                = render @albums_pg
                .text-center
                  = paginate @albums_pg, :param_name => 'album'
/javascript:
/  var data = {'data-date-format': 'YYYY-MM-DD hh:mm' };
/  $(function() {
/    $('.datetimepicker').attr(data);
/    $('.datetimepicker').datetimepicker( {
/      format: 'YYYY/MM/DD hh:mm'
/    });
/  });
/script type='text/javascript' src='../bootstrap-datepicker-1.6.4-dist/js/bootstrap-datepicker.min.js'
/script type='text/javascript' src='../bootstrap-datepicker-1.6.4-dist/locales/bootstrap-datepicker.ja.min.js'

app/views/users/withdraw.html.slim
.withdraw-page-bg
  .withdraw-top
    .row.withdraw-text.text-center
      p
        = t('.text1')
      br
      p
        = t('.text2')
      br
      p
        span = t('.text_bold')
        = t('.text3')
      br
      p
        = t('.text4')

    .row.withdraw-btn.text-center
      .col-xs-4
      .col-xs-2
        = link_to t('.btn1'), user_path(@theuser), class:"btn-success btn btn-lg"
      .col-xs-2
        button#js-modal-open-btn.btn.btn-danger.btn-lg.col-xs-8.btn-icon-color
          = t('.btn2')
      .col-xs-4

  div id='js-overlay'
    div id='js-modal-window'
      .modal-message-box
        div
          = t('app.common.confirm')
        div
          = t('app.common.confirm_del')
      button id='js-modal-close-btn' = t('app.common.cancel')
      = link_to t('posts.edit.delete'), switch_path(@theuser), method: :delete, id:'js-delete-confirmation-btn', class:'modal-delete-btn'