config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'homes#top', as: 'top'
    get 'about', to: 'homes#about', as: 'about'
    get 'data', to: 'analyses#data', as: 'data'
    get 'rank', to: 'analyses#rank', as: 'rank'
    get 'searches', to: 'searches#search', as: 'search'
    get 'bookmarks', to: 'bookmarks#index', as: 'bookmark'

    resources :users, only: %i[show edit update]
    get 'users/:user_id/withdraw', to: 'users#withdraw', as: 'withdraw'
    patch 'users/:user_id/switch', to: 'users#switch', as: 'switch'
    resources :posts, only: %i[index show edit create update destroy] do
      resource :likes, only: %i[index create destroy]
      resources :post_comments, only: %i[create update destroy]
      collection do
        get :cities_select
      end
    end
    resources :albums, only: %i[index show edit create update destroy] do
      resource :bookmarks, only: %i[create destroy]
    end

    resources :prefectures, only: %i[index]
    resources :genres, only: %i[index create update destroy]
    get 'budget', to: 'genres#budget', as: 'budget'
    get 'age', to: 'genres#age', as: 'age'
    get 'nation', to: 'genres#nation', as: 'nation'
    resources :events
  end
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  include Page
  include RankData

  # GET /data
  # data_path
  def data
    # Japanese User Ranking
    posts_jp = Post.eager_load(:user).jp
    albums_jp = Album.eager_load(:user).jp
    @jp_area_ranks = Prefecture.find(pref_rank(posts_jp))
    @jp_genre_ranks = Genre.find(genre_rank(posts_jp))
    @jp_budget_ranks = budget_rank(albums_jp)

    # Other Nationalities User Ranking
    posts = Post.eager_load(:user).other
    albums = Album.eager_load(:user).other
    @others_area_ranks = Prefecture.find(pref_rank(posts))
    @others_genre_ranks = Genre.find(genre_rank(posts))
    @others_budget_ranks = budget_rank(albums)

    # Highcharts
    @jp_10_genre_ranks = Genre.find(genre_rank_10(posts_jp))
    @jp_10_pref_ranks = Prefecture.find(pref_rank_10(posts_jp))
    @others_10_genre_ranks = Genre.find(genre_rank_10(posts))
    @others_10_pref_ranks = Prefecture.find(pref_rank_10(posts))
    locale = params[:locale]
    @jp_genre_data = highchart_g_clc(@jp_10_genre_ranks, locale)
    @jp_genre_graph = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ defaultSeriesType: 'pie', margin: [50, 200, 60, 170] })
      f.title(text: t('analyses.data.graph_genre_t'))
      f.series(name: t('analyses.data.graph_genre_n'), data: @jp_genre_data, type: 'pie')
      f.legend(align: 'right', layout: 'vertical', style: { left: 'auto', bottom: 'auto', right: '100px', top: '100px' })
      f.plot_options(pie: { allowPointSelect: true, cursor: 'pointer', dataLabels: { enabled: true, color: 'white', style: { fontSize: '15px', font: '33px Trebuchet MS, Verdana, sans-serif' } } })
    end
    @jp_pref_data = highchart_p_clc(@jp_10_pref_ranks, locale)
    @jp_pref_graph = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ defaultSeriesType: 'pie', margin: [50, 200, 60, 170] })
      f.title(text: t('analyses.data.graph_pref_t'))
      f.series(name: t('analyses.data.graph_pref_n'), data: @jp_pref_data, type: 'pie')
      f.legend(align: 'right', layout: 'vertical', style: { left: 'auto', bottom: 'auto', right: '50px', top: '100px' })
      f.plot_options(pie: { allowPointSelect: true, cursor: 'pointer', dataLabels: { enabled: true, color: 'white', style: { fontSize: '15px', font: '33px Trebuchet MS, Verdana, sans-serif' } } })
    end
    @jp_budget_data = highchart_b_clc(albums_jp)
    @jp_budget_graph = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ defaultSeriesType: 'pie', margin: [50, 200, 60, 170] })
      f.title(text: t('analyses.data.graph_budget_t'))
      f.series(name: t('analyses.data.graph_budget_n'), data: @jp_budget_data, type: 'pie')
      f.legend(align: 'right', layout: 'vertical', style: { left: 'auto', bottom: 'auto', right: '50px', top: '100px' })
      f.plot_options(pie: { allowPointSelect: true, cursor: 'pointer', dataLabels: { enabled: true, color: 'white', style: { fontSize: '15px', font: '33px Trebuchet MS, Verdana, sans-serif' } } })
    end
    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, 'rgb(23, 35, 60)'],
            [1, 'rgb(23, 35, 60)']
          ]
        },
        borderWidth: 5,
        plotBackgroundColor: 'rgb(27, 39, 56)',
        plotShadow: true,
        marginBottom: 40,
        marginLeft: 40,
        marginRight: 40
      )
      f.lang(thousandsSep: ',')
      f.colors(['#f7a35c', '#8085e9', '#f15c80', '#90ed7d', '#e4d354'])
      f.title(
        style: { 'color': '#fff', 'font-size': '25px' },
        align: 'center',
        widthAdjust: '-20'
      )
    end
    @others_genre_data = highchart_g_clc(@others_10_genre_ranks, locale)
    @others_genre_graph = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ defaultSeriesType: 'pie', margin: [50, 200, 60, 170] })
      f.colors(['#4682B4', '#2E8B57', '#e4d354'])
      f.title(text: t('analyses.data.graph_genre_t'))
      f.series(name: t('analyses.data.graph_genre_n'), data: @others_genre_data, type: 'pie')
      f.legend(align: 'right', layout: 'vertical', style: { left: 'auto', bottom: 'auto', right: '100px', top: '100px' })
      f.plot_options(pie: { allowPointSelect: true, cursor: 'pointer', dataLabels: { enabled: true, color: 'white', style: { fontSize: '15px', font: '33px Trebuchet MS, Verdana, sans-serif' } } })
    end
    @others_pref_data = highchart_p_clc(@others_10_pref_ranks, locale)
    @others_pref_graph = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ defaultSeriesType: 'pie', margin: [50, 200, 60, 170] })
      f.colors(['#4682B4', '#2E8B57', '#e4d354'])
      f.title(text: t('analyses.data.graph_pref_t'))
      f.series(name: t('analyses.data.graph_pref_n'), data: @others_pref_data, type: 'pie')
      f.legend(align: 'right', layout: 'vertical', style: { left: 'auto', bottom: 'auto', right: '100px', top: '100px' })
      f.plot_options(pie: { allowPointSelect: true, cursor: 'pointer', dataLabels: { enabled: true, color: 'white', style: { fontSize: '15px', font: '33px Trebuchet MS, Verdana, sans-serif' } } })
    end
    @others_budget_data = highchart_b_clc(albums)
    @others_budget_graph = LazyHighCharts::HighChart.new('pie') do |f|
      f.chart({ defaultSeriesType: 'pie', margin: [50, 200, 60, 170] })
      f.colors(['#4682B4', '#2E8B57', '#e4d354'])
      f.title(text: t('analyses.data.graph_budget_t'))
      f.series(name: t('analyses.data.graph_budget_n'), data: @others_budget_data, type: 'pie')
      f.legend(align: 'right', layout: 'vertical', style: { left: 'auto', bottom: 'auto', right: '50px', top: '100px' })
      f.plot_options(pie: { allowPointSelect: true, cursor: 'pointer', dataLabels: { enabled: true, color: 'white', style: { fontSize: '15px', font: '33px Trebuchet MS, Verdana, sans-serif' } } })
    end
  end

  # GET /rank
  # rank_path
  def rank
    @genres = Genre.where.not(id: 1).all
    @posts = page_8(Post)
    @albums = page_8(Album)

    # Ranking
    # --- Post-Like Ranking
    @post_like_ranks = Post.find(post_rank(Like))
    # --- Post-Comment
    @post_comment_ranks = Post.find(post_rank(PostComment))
    # --- Album-Bookmark
    @album_bookmark_ranks = Album.find(album_rank(Bookmark))
  end

end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/views/analyses/_album_rank.html.slim
.genre-post-rank
  .col-xs-12.bg-success.genre-post-rank__margin-bottom
    - if i == 1 || i == 2 || i == 3
      .col-xs-1
        - if i == 1 then
          .fas.fa-crown style="color:#ffd700; font-size: 30px;"
        - elsif i == 2 then
          i.fas.fa-crown style="color:#aaaaaa; font-size: 30px;"
        - elsif i == 3 then
          i.fas.fa-crown style="color:#d2691e; font-size: 30px;"
      .col-xs-2
      .col-xs-9
    -else
      .col-xs-1
        h3.genre-post-rank__number
          = i
          span
            = t('analyses.rank.grade')

  .col-xs-12
    .col-xs-4
      .genre-post-rank__left-box
        .genre-post-rank__image-box
          .genre-post-rank__icon
            = link_to album_path(album) do
              = attachment_image_tag album, :image, fallback:"img/book.png", class:"field", size:"85x65"
        .genre-post-rank__icon-box
          .col-xs-12
            .col-xs-4
              .genre-post-rank__bookmark-icon
                i.fas.fa-bookmark style="font-size:20px; color:#0099cc;"
            .col-xs-4
              .genre-post-rank__bookmark-count
                - if album.bookmarks.nil?
                  span
                    | 0
                - else
                  span
                  = album.bookmarks.count
    .col-xs-8
      table.table.table-bordered
        thead
          tr
            th
              = t('analyses.rank.user')
            td
              = album.user.name
          tr
            th
              = t('analyses.rank.rate')
            td
              = album.rate
          tr
            th
              = t('analyses.rank.title')
            td
              = album.title
          tr
            th
              = t('analyses.rank.genre')
            td
              = album.genre.name
          tr
            th
              = t('analyses.rank.create')
            td
              = album.created_at
  .col-xs-12
    = link_to post_path(post) do
      h5
        = t('analyses.rank.have_look')

app/views/analyses/_jp_rank.html.slim
.jp-data
  .jp-data__title.text-center
    .jp-data__title--text
      = t('analyses.data.subtitle_jp')
  .jp-data__box
    .jp-data__rank-unit
      .jp-data__rank-unit--area
        .col-xs-12
          .jp-data__rank-unit--subtitle
            = t('analyses.data.area_rank')
        .col-xs-12
          - if jp_area_ranks.nil?
            h4
              = t('common.no_data')
          - else
            - jp_area_ranks.each.with_index(1) do |pref, i|
              .col-xs-4
                .jp-data__area-rank
                  .jp-data__area-rank-icon
                    - if i == 1 then
                      i.fas.fa-crown style="color:#ffd700; font-size:30px;"
                    - elsif i == 2 then
                      i.fas.fa-crown style="color:#aaa; font-size:30px;"
                    - elsif i == 3 then
                      i.fas.fa-crown style="color:#d2691e; font-size:30px;"
                  .jp-data__area-rank-img
                    .map-img
                        // 投稿のarea検索ページに推移したいが、area_idとの差を埋められない
                        //= link_to prefectures_path(area_id: genre.id)
                        div class="map-img__#{ pref.id }"
                  .jp-data__area-rank-name
                    - if params[:locale] = 'ja'
                      = pref.name
                    - else
                      = pref.en_name
    .jp-data__rank-unit
      .jp-data__rank-unit--genre
        .col-xs-12
          .jp-data__rank-unit--subtitle
            = t('analyses.data.genre_rank')
        .col-xs-12
        .col-xs-12
          - if jp_genre_ranks.nil?
            h4
              = t('common.no_data')
          - else
            - jp_genre_ranks.each.with_index(1) do |genre, i|
              .col-xs-4
                .jp-data__genre-rank
                  .jp-data__genre-rank-icon
                    - if i == 1 then
                      i.fas.fa-crown style="color:#ffd700; font-size:30px;"
                    - elsif i == 2 then
                      i.fas.fa-crown style="color:#aaa; font-size:30px;"
                    - elsif i == 3 then
                      i.fas.fa-crown style="color:#d2691e; font-size:30px;"
                  .jp-data__genre-rank-img
                    .genre-img
                      = link_to genres_path(id: genre.id)
                        div class="genre-img__#{ genre.id }"
                  .jp-data__genre-rank-name
                    - if params[:locale] = 'ja'
                      = genre.name
                    - else
                      = genre.en_name
    .jp-data__rank-unit
      .jp-data__rank-unit--budget
        .col-xs-12
          .jp-data__rank-unit--subtitle
            = t('analyses.data.budget_rank')
        .col-xs-12
          - if jp_budget_ranks.nil?
            h4
              = t('common.no_data')
          - else
            - jp_budget_ranks.each.with_index(1) do |budget, i|
              .col-xs-4
                .jp-data__budget-rank
                  .jp-data__budget-rank-icon
                    - if i == 1 then
                      i.fas.fa-crown style="color:#ffd700; font-size:30px;"
                    - elsif i == 2 then
                      i.fas.fa-crown style="color:#aaa; font-size:30px;"
                    - elsif i == 3 then
                      i.fas.fa-crown style="color:#d2691e; font-size:30px;"
                  .jp-data__budget-rank-img
                    .budget-img
                      / 動的にimgを変更する予定
                      /div class="budget-img__#{ .id }"
                  .jp-data__budget-rank-name
                    = budget

app/views/analyses/_others_rank.html.slim
.jp-data
  .jp-data__title.text-center
    .jp-data__title--text
      = t('analyses.data.subtitle_ot')
  .jp-data__box
    .jp-data__rank-unit
      .jp-data__rank-unit--area
        .col-xs-12
          .jp-data__rank-unit--subtitle
            = t('analyses.data.area_rank')
        .col-xs-12
          - if @others_area_ranks.nil?
            h4
              = t('common.no_data')
          - else
            - @others_area_ranks.each.with_index(1) do |pref, i|
              .col-xs-4
                .jp-data__area-rank
                  .jp-data__area-rank-icon
                    - if i == 1 then
                      i.fas.fa-crown style="color:#ffd700; font-size:30px;"
                    - elsif i == 2 then
                      i.fas.fa-crown style="color:#aaa; font-size:30px;"
                    - elsif i == 3 then
                      i.fas.fa-crown style="color:#d2691e; font-size:30px;"
                  .jp-data__area-rank-img
                    .map-img
                        // 投稿のarea検索ページに推移したいが、area_idとの差を埋められない
                        //= link_to prefectures_path(area_id: genre.id)
                        div class="map-img__#{ pref.id }"
                  .jp-data__area-rank-name
                    = pref.name
    .jp-data__rank-unit
      .jp-data__rank-unit--genre
        .col-xs-12
          .jp-data__rank-unit--subtitle
            = t('analyses.data.genre_rank')
        .col-xs-12
          - if @others_genre_ranks.nil?
            h4
              = t('common.no_data')
          - else
            - @others_genre_ranks.each.with_index(1) do |genre, i|
              .col-xs-4
                .jp-data__genre-rank
                  .jp-data__genre-rank-icon
                    - if i == 1 then
                      i.fas.fa-crown style="color:#ffd700; font-size:30px;"
                    - elsif i == 2 then
                      i.fas.fa-crown style="color:#aaa; font-size:30px;"
                    - elsif i == 3 then
                      i.fas.fa-crown style="color:#d2691e; font-size:30px;"
                  .jp-data__genre-rank-img
                    .genre-img
                      = link_to genres_path(id: genre.id)
                        div class="genre-img__#{ genre.id }"
                  .jp-data__genre-rank-name
                    = genre.name
    .jp-data__rank-unit
      .jp-data__rank-unit--budget
        .col-xs-12
          .jp-data__rank-unit--subtitle
            = t('analyses.data.budget_rank')
        .col-xs-12
          - if @others_budget_ranks.nil?
            h4
              = t('common.no_data')
          - else
            - @others_budget_ranks.each.with_index(1) do |budget, i|
              .col-xs-4
                .jp-data__budget-rank
                  .jp-data__budget-rank-icon
                    - if i == 1 then
                      i.fas.fa-crown style="color:#ffd700; font-size:30px;"
                    - elsif i == 2 then
                      i.fas.fa-crown style="color:#aaa; font-size:30px;"
                    - elsif i == 3 then
                      i.fas.fa-crown style="color:#d2691e; font-size:30px;"
                  .jp-data__budget-rank-img
                    .budget-img
                      / 動的にimgを変更する予定
                      /div class="budget-img__#{ .id }"
                  .jp-data__budget-rank-name
                    = budget

app/views/analyses/_post_rank.html.slim
.genre-post-rank
  .col-xs-12.genre-post-rank__margin-bottom
    - if i == 1 || i == 2 || i == 3
      .col-xs-1
        - if i == 1 then
          .fas.fa-crown style="color:#ffd700; font-size: 30px;"
        - elsif i == 2 then
          i.fas.fa-crown style="color:#aaaaaa; font-size: 30px;"
        - elsif i == 3 then
          i.fas.fa-crown style="color:#d2691e; font-size: 30px;"
      .col-xs-2
      .col-xs-9
    -else
      .col-xs-2
        h4.genre-post-rank__number
          = i
          span
            = t('analyses.rank.grade')
  .col-xs-12
    .col-xs-4
      .genre-post-rank__left-box
        .genre-post-rank__image-box
          = link_to post_path(post) do
            = attachment_image_tag post, :image, fallback:"img/no_photo.png", class:"field", class: 'genre-post-rank__icon', size:"85x65"
        .genre-post-rank__icon-box
          .col-xs-12
            .col-xs-4
              .genre-post-rank__like-icon.pull-left
                i.fa.fa-heart aria-hidden="true" style="color: red; font-size:20px;"
            .col-xs-4
              .genre-post-rank__like-count
                - if post.likes.nil?
                  span
                    | 0
                - else
                  span
                    = post.likes.count
          .col-xs-12
            .col-xs-4
              .genre-post-rank__comment-icon
                i.glyphicon.glyphicon-comment style="font-size:20px;"
            .col-xs-4
              .genre-post-rank__comment-count
                - if post.post_comments.nil?
                  span
                    | 0
                - else
                  span
                  = post.post_comments.count
    .col-xs-8.rank-post-like__table
      table.table.table-bordered
        thead
          tr
            th
              = t('analyses.rank.user')
            td
              = post.user.name
          tr
            th
              = t('analyses.rank.rate')
            td
              = post.rate
          tr
            th
              = t('analyses.rank.title')
            td
              = post.title
          tr
            th
              = t('analyses.rank.genre')
            td
              = post.genre.name
          tr
            th
              = t('analyses.rank.pref')
            td
              = post.prefecture.name
          tr
            th
              = t('analyses.rank.create')
            td
              - if params[:locale] == 'ja'
                = ja_time_fmt post.created_at
              - else
                = time_fmt post.created_at
  .col-xs-12
    = link_to post_path(post) do
      h5
        = t('analyses.rank.have_look')

app/views/analyses/data.html.slim
.data-page-bg
  .top-wrapper
    .row
      .col-xs-12.text-center
        h1
          = t('.title')
      .row
        .tab-menu
          ul.nav.nav-tabs.text-center role="tablist"
            li.active role="presentation"
              a.text-cetner aria-control="tab_a" data-toggle="tab" href="#tab_a" role="tab"
                = t('analyses.data.tab_rate')
            li role="presentation"
              a.text-cetner aria-control="tab_b" data-toggle="tab" href="#tab_b" role="tab"
                = t('analyses.data.tab_rank')
      .row
        .tab-content
          .tab-pane.active id="tab_a" role="tabpanel"
            .col-xs-12
              .col-xs-6
                .jp-data
                  .jp-data__title
                    .jp-data__title--text.text-center
                      = t('analyses.data.subtitle_jp')
                = high_chart_globals(@chart_globals)
                = high_chart('sample', @jp_genre_graph)
                  = raw "options.tooltip.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';},"
                  = raw "options.plotOptions.pie.dataLabels.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';}"
                = high_chart('sample2', @jp_pref_graph)
                  = raw "options.tooltip.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';},"
                  = raw "options.plotOptions.pie.dataLabels.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';}"
                = high_chart('sample3', @jp_budget_graph)
                  = raw "options.tooltip.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';},"
                  = raw "options.plotOptions.pie.dataLabels.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';}"
              .col-xs-6
                .jp-data
                  .jp-data__title
                    .jp-data__title--text.text-center
                      = t('analyses.data.subtitle_ot')
                = high_chart('sample4', @others_genre_graph)
                  = raw "options.tooltip.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';},"
                  = raw "options.plotOptions.pie.dataLabels.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';}"
                = high_chart('sample5', @others_pref_graph)
                  = raw "options.tooltip.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';},"
                  = raw "options.plotOptions.pie.dataLabels.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';}"
                = high_chart('sample6', @others_budget_graph)
                  = raw "options.tooltip.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';},"
                  = raw "options.plotOptions.pie.dataLabels.formatter = function() {return '<b> '+ this.point.name +'</b>: '+ this.y +' %';}"
          .tab-pane id="tab_b" role="tabpanel"
            .col-xs-12
              .col-xs-6
                = render 'jp_rank', jp_area_ranks: @jp_area_ranks, jp_genre_ranks: @jp_genre_ranks, jp_budget_ranks: @jp_budget_ranks
              .col-xs-6
                = render 'others_rank', others_area_ranks: @others_area_ranks, others_genre_ranks: @others_genre_ranks, others_budget_ranks: @others_budget_ranks

script src='https://code.highcharts.com/highcharts.js'

app/views/analyses/rank.html.slim
.rank-page-bg
  .margin-wrapper
    .top-wrapper
      .row
        .col-xs-12.margin-bottom-40.text-center
          h1
            = t('analyses.rank.pagetitle')
          p
            = t('analyses.rank.subtitle')
      // Post Like
      .row
        .col-xs-12
      .row
        .col-xs-4
          h2
            = t('analyses.rank.like')
          - if @post_like_genre_ranks.present?
            h4 = @post_like_genre_ranks.first.genre.name
            - @pickgenre_post_like_ranks.each.with_index(1) do |post, i|
              = render 'post_rank', post: post, i: i
          - else
            - @post_like_ranks.each.with_index(1) do |post, i|
              = render 'post_rank', post: post, i: i

        // Post Comment数ランキング
        .col-xs-4
          h2
            = t('analyses.rank.comment')
          - if @post_comment_genre_ranks.present?
            h4 = @post_comment_genre_ranks.first.genre.name
            - @pickgenre_post_comment_ranks.each.with_index do |post, i|
                = render 'post_rank', post: post, i: i
          - else
            - @post_comment_ranks.each.with_index(1) do |post, i|
              = render 'post_rank', post: post, i: i

        // Album Bookmark数ランキング
        .col-xs-4
          h2
            = t('analyses.rank.bookmark')
          - if @album_bookmark_genre_ranks.present?
            - @album_bookmark_genre_ranks.each.with_index(1) do |album, i|
              = render 'album_rank', album: album, i: i
          - else
            - @album_bookmark_ranks.each.with_index(1) do |album, i|
              = render 'album_rank', album: album, i: i