config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'homes#top', as: 'top'
    get 'about', to: 'homes#about', as: 'about'
    get 'data', to: 'analyses#data', as: 'data'
    get 'rank', to: 'analyses#rank', as: 'rank'
    get 'searches', to: 'searches#search', as: 'search'
    get 'bookmarks', to: 'bookmarks#index', as: 'bookmark'

    resources :users, only: %i[show edit update]
    get 'users/:user_id/withdraw', to: 'users#withdraw', as: 'withdraw'
    patch 'users/:user_id/switch', to: 'users#switch', as: 'switch'
    resources :posts, only: %i[index show edit create update destroy] do
      resource :likes, only: %i[index create destroy]
      resources :post_comments, only: %i[create update destroy]
      collection do
        get :cities_select
      end
    end
    resources :albums, only: %i[index show edit create update destroy] do
      resource :bookmarks, only: %i[create destroy]
    end

    resources :prefectures, only: %i[index]
    resources :genres, only: %i[index create update destroy]
    get 'budget', to: 'genres#budget', as: 'budget'
    get 'age', to: 'genres#age', as: 'age'
    get 'nation', to: 'genres#nation', as: 'nation'
    resources :events
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :bigint           not null, primary key
#  allday     :string(255)
#  body       :text(65535)
#  end        :datetime
#  start      :datetime
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  genre_id   :integer          not null
#  user_id    :integer          not null
#
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :genre
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!

  include UserStatus
  include Page

  # GET /events
  # GET /events.json
  # events_path
  def index
    @events = Event.all
    redirect_to user_path(current_user)
  end

  # GET /events/:id
  # GET /events/1.json
  # event_path
  def show
    @theevent = find_event(params[:id])
    if @theevent.user == current_user
      @theuser = current_user
    else
      redirect_to top_path
    end
  end

  # POST /events
  # POST /events.json
  # events_path
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    @events = Event.where(user_id: current_user.id)
    respond_to do |format|
      format.js if @event.save
      format.js { render :modal_create }
    end
  end

  # PATCH /event/:id
  # event_path
  def update
    @event = find_event(params[:id])
    @events = Event.where(user_id: current_user.id)
    respond_to do |format|
      format.js if @event.update(event_params)
    end
  end

  # DELETE /event/:id
  # event_path
  def destroy
    event = Event.find(params[:id])
    @user = event.user
    @events = Event.where(user_id: current_user.id)

    respond_to do |format|
      format.js if event.destroy
    end
  end

  private

  def find_event(event_id)
    Event.find(event_id)
  end

  def find_user(user_id)
    User.find(user_id)
  end

  def event_params
    params.require(:event).permit(:user_id, :genre_id, :title, :body, :start, :end)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit_form.html.slim
- events.each do |event|
  .modal.fade id="inputScheduleEditForm#{ event.id }" tabindex='-1'
    .event-form
      .event-form__title
        .col-xs-12
          .col-xs-11
            h2
              = t('users.show.edit_form')
          .col-xs-1.event-form__title--btn
            button type='button' class='btn btn-default' data-dismiss="modal"
              | X
      .event-form__form
        = form_with(model: event, url: event_path(event), method: :patch, remote: true) do |f|
          .form-window.row
            = f.label t('users.show.f_title')
            br
            = f.text_field :title
          .form-window.row
            =f.label t('users.show.f_description')
            br
            = f.text_area :body
          .form-window.row
            = f.label t('users.show.f_genre')
            br
            - if params[:locale] == 'ja'
              = f.collection_select :genre_id, Genre.all, :id, :name, prompt: "Please select"
            - else
              = f.collection_select :genre_id, Genre.all, :id, :en_name, prompt: "Please select"
          .form-window.row
            = f.label t('users.show.f_start')
            br
            = f.text_field :start, data: {date_format: 'YYYY/MM/DD hh:mm' }, class:"col-xs-8 datetimepicker", placeholder: 'YYYY/MM/DD hh:mm'
          .form-window.row
            = f.label t('users.show.f_end')
            br
            = f.text_field :end, data: {date_format: 'YYYY/MM/DD hh:mm' }, class:"col-xs-8 datetimepicker", placeholder: 'YYYY/MM/DD hh:mm'
          .event-form__form--btn.action.row
            .col-xs-12
              .col-xs-1
                = f.submit t('users.show.f_update'), class:"btn btn-success"
              .col-xs-1
              .col-xs-1
                = link_to t('users.show.f_delete'), event_path(event), method: :delete, remote: true, data: { confirm: t('app.common.confirm_del') }, class:"btn btn-danger pull-right"

app/views/events/_form.html.slim
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @event.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :genre_id
    = f.number_field :genre_id
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :start_date
    = f.datetime_select :start_date
  .field
    = f.label :end_date
    = f.datetime_select :end_date
  .field
    = f.label :budget
    = f.text_field :budget
  .field
    = f.label :mean
    = f.text_field :mean
  .field
    = f.label :purpose
    = f.text_field :purpose
  .field
    = f.label :people
    = f.number_field :people
  .field
    = f.label :memo
    = f.text_field :memo
  .actions = f.submit

app/views/events/create.js.erb
$('#error-pop').remove();
$('input[type="text"]').val('');
$('#inputScheduleForm').modal('hide');
$('#inputEditForm').html("<%= j(render 'events/edit_form',  events: @events) %>");
$('#calendar').fullCalendar('refetchEvents')

app/views/events/destroy.js.erb
$('.modal-backdrop').remove();
$('input[type="text"]').val('');
$('#inputScheduleEditForm').modal('hide');
$('#inputEditForm').html("<%= j(render 'events/edit_form',  events: @events) %>");
$('#calendar').fullCalendar('refetchEvents')

app/views/events/edit.html.slim
h1 Editing event

== render 'form'

=> link_to 'Show', @event
'|
=< link_to 'Back', events_path

app/views/events/index.html.slim
h1 Listing events

table
  thead
    tr
      th User
      th title
      th body
      th start
      th end


  tbody
    - @events.each do |event|
      tr
        td = event.user_id
        td = event.genre_id
        td = event.title
        td = event.body
        td = event.start
        td = event.end
        td = link_to 'Show', event
        td = link_to 'Edit', edit_event_path(event)
        td = link_to 'Destroy', event, data: { confirm: t('app.common.confirm_del') }, method: :delete

br

= link_to 'New Event', new_event_path

app/views/events/modal_create.js.erb
$('.modal-backdrop').remove();
$('input[type="text"]').val('');
$('#error-pop').html("<%= j(render 'layouts/error_message', model: @event) %>");

app/views/events/new.html.slim
h1 New event

== render 'form'

= link_to 'Back', events_path

app/views/events/show.html.slim
.container
  .top-wrapper
    .row
      .col-xs-12
        .evnet-detail
          .evnet-detail-box
            .event-detail-box__title
              = t('events.show.user_id')
            .event-detail-box__content
              = @theevent.user_id

            .event-detail-box__title
              = t('events.show.user')
            .event-detail-box__content
              = @theevent.user.name

            .event-detail-box__title
              = t('events.show.title')
            .event-detail-box__content
              = @theevent.title

            .event-detail-box__title
              = t('events.show.body')
            .event-detail-box__content
              - if @theevent.body.nil?
                = t('events.show.none')
              - else
                = @theevent.body

            .event-detail-box__title
              = t('events.show.start')
            .event-detail-box__content
              = @theevent.start

            .event-detail-box__title
              = t('events.show.end')
            .event-detail-box__content
              = @theevent.end

          .row
            .col-xs-6
              .event-detail__btn
                .event-detail__btn-text
                  = link_to t('app.common.back'), user_path(@theuser), class:"btn btn-success"
            .col-xs-6
              .event-detail__btn
                .event-detail__btn-text
                  = link_to t('app.common.delete'), event_path(@theevent), method: :delete, data: { confirm: t('app.common.confirm_del') }, class:"btn btn-danger pull-right"
                  /'|
                  /= link_to 'Edit', events_path

app/views/events/update.js.erb
$('.modal-backdrop').remove();
$('#inputScheduleEditForm').modal('hide');
$('#inputEditForm').html("<%= j(render 'events/edit_form',  events: @events) %>");
$('#calendar').fullCalendar('refetchEvents')