config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root to: 'homes#top', as: 'top'
    get 'about', to: 'homes#about', as: 'about'
    get 'data', to: 'analyses#data', as: 'data'
    get 'rank', to: 'analyses#rank', as: 'rank'
    get 'searches', to: 'searches#search', as: 'search'
    get 'bookmarks', to: 'bookmarks#index', as: 'bookmark'

    resources :users, only: %i[show edit update]
    get 'users/:user_id/withdraw', to: 'users#withdraw', as: 'withdraw'
    patch 'users/:user_id/switch', to: 'users#switch', as: 'switch'
    resources :posts, only: %i[index show edit create update destroy] do
      resource :likes, only: %i[index create destroy]
      resources :post_comments, only: %i[create update destroy]
      collection do
        get :cities_select
      end
    end
    resources :albums, only: %i[index show edit create update destroy] do
      resource :bookmarks, only: %i[create destroy]
    end

    resources :prefectures, only: %i[index]
    resources :genres, only: %i[index create update destroy]
    get 'budget', to: 'genres#budget', as: 'budget'
    get 'age', to: 'genres#age', as: 'age'
    get 'nation', to: 'genres#nation', as: 'nation'
    resources :events
  end
end

app/models/prefecture.rb
# == Schema Information
#
# Table name: prefectures
#
#  id         :bigint           not null, primary key
#  en_name    :string(255)      not null
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Prefecture < ApplicationRecord
  has_many :cities, dependent: :destroy
  has_many :posts
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController

  include PrefPost
  include Page

  # GET prefectures/
  # prefectures_path
  def index
    if params[:area_id]
      area = params[:area_id]
      @posts = area_choice(area)
    elsif params[:pref_id]
      pref = params[:pref_id]
      @posts = pref_choice(pref)
    else
      @posts = page_8(Post)
    end
  end

end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/prefectures/_area_list.html.slim
//日本地図横の地域リスト
ol
  ul#area
    .col-xs-12
      li
        = link_to t('prefectures.index.hokkaido_area'), prefectures_path(area_id: 1)
    .col-xs-12
      .prefs
        .prefs__name
          = link_to t('prefectures.index.hokkaido'), prefectures_path(pref_id: 1)
    .col-xs-12
      li
        = link_to t('prefectures.index.tohoku_area'), prefectures_path(area_id: 2)
    .col-xs-12
      .prefs
        .prefs__name
          = link_to t('prefectures.index.aomori'), prefectures_path(pref_id: 2)
          | , 
          = link_to t('prefectures.index.iwate'), prefectures_path(pref_id: 3)
          | , 
          = link_to t('prefectures.index.miyagi'), prefectures_path(pref_id: 4)
          | , 
          = link_to t('prefectures.index.akita'), prefectures_path(pref_id: 5)
          | , 
          = link_to t('prefectures.index.yamagata'), prefectures_path(pref_id: 6)
          | , 
          = link_to t('prefectures.index.fukushima'), prefectures_path(pref_id: 7)
    .col-xs-12
      li
        = link_to t('prefectures.index.hokuriku_area'), prefectures_path(area_id: 3)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.niigata'), prefectures_path(pref_id: 15)
          | , 
          = link_to t('prefectures.index.toyama'), prefectures_path(pref_id: 16)
          | , 
          = link_to t('prefectures.index.ishikawa'), prefectures_path(pref_id: 17)
          | , 
          = link_to t('prefectures.index.fukui'), prefectures_path(pref_id: 18)
          | , 
          = link_to t('prefectures.index.yamanashi'), prefectures_path(pref_id: 19)
          | , 
          = link_to t('prefectures.index.nagano'), prefectures_path(pref_id: 20)
    .col-xs-12
      li
        = link_to t('prefectures.index.kanto_area'), prefectures_path(area_id: 4)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.tokyo'), prefectures_path(pref_id: 13)
          | , 
          = link_to t('prefectures.index.ibaraki'), prefectures_path(pref_id: 8)
          | , 
          = link_to t('prefectures.index.tochigi'), prefectures_path(pref_id: 9)
          | , 
          = link_to t('prefectures.index.gunma'), prefectures_path(pref_id: 10)
          | , 
          = link_to t('prefectures.index.saitama'), prefectures_path(pref_id: 11)
          | , 
          = link_to t('prefectures.index.chiba'), prefectures_path(pref_id: 12)
          | , 
          = link_to t('prefectures.index.kanagawa'), prefectures_path(pref_id: 14)
    .col-xs-12
      li
        = link_to t('prefectures.index.tokai_area'), prefectures_path(area_id: 5)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.gifu'), prefectures_path(pref_id: 21)
          | , 
          = link_to t('prefectures.index.sizuoka'), prefectures_path(pref_id: 22)
          | , 
          = link_to t('prefectures.index.aichi'), prefectures_path(pref_id: 23)
          | , 
          = link_to t('prefectures.index.mie'), prefectures_path(pref_id: 24)
    .col-xs-12
      li
        = link_to t('prefectures.index.kinki_area'), prefectures_path(area_id: 6)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.kyoto'), prefectures_path(pref_id: 26)
          | , 
          = link_to t('prefectures.index.osaka'), prefectures_path(pref_id: 27)
          | , 
          = link_to t('prefectures.index.siga'), prefectures_path(pref_id: 25)
          | , 
          = link_to t('prefectures.index.hyogo'), prefectures_path(pref_id: 28)
          | , 
          = link_to t('prefectures.index.nara'), prefectures_path(pref_id: 29)
          | , 
          = link_to t('prefectures.index.wakayama'), prefectures_path(pref_id: 30)
    .col-xs-12
      li
        = link_to t('prefectures.index.chugoku_area'), prefectures_path(area_id: 7)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.tottori'), prefectures_path(pref_id: 31)
          | , 
          = link_to t('prefectures.index.shimane'), prefectures_path(pref_id: 32)
          | , 
          = link_to t('prefectures.index.okayama'), prefectures_path(pref_id: 33)
          | , 
          = link_to t('prefectures.index.hiroshima'), prefectures_path(pref_id: 34)
          | , 
          = link_to t('prefectures.index.yamaguchi'), prefectures_path(pref_id: 35)
    .col-xs-12
      li
        = link_to t('prefectures.index.shikoku_area'), prefectures_path(area_id: 8)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.tokushima'), prefectures_path(pref_id: 36)
          | , 
          = link_to t('prefectures.index.kagawa'), prefectures_path(pref_id: 37)
          | , 
          = link_to t('prefectures.index.ehime'), prefectures_path(pref_id: 38)
          | , 
          = link_to t('prefectures.index.kochi'), prefectures_path(pref_id: 39)
    .col-xs-12
      li
        = link_to t('prefectures.index.kyushu_area'), prefectures_path(area_id: 9)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.fukuoka'), prefectures_path(pref_id: 40)
          | , 
          = link_to t('prefectures.index.saga'), prefectures_path(pref_id: 41)
          | , 
          = link_to t('prefectures.index.nagasaki'), prefectures_path(pref_id: 42)
          | , 
          = link_to t('prefectures.index.oita'), prefectures_path(pref_id: 44)
          | , 
          = link_to t('prefectures.index.kumamoto'), prefectures_path(pref_id: 43)
          | , 
          = link_to t('prefectures.index.miyazaki'), prefectures_path(pref_id: 45)
          | , 
          = link_to t('prefectures.index.kagoshima'), prefectures_path(pref_id: 46)
    .col-xs-12
      li
        = link_to t('prefectures.index.okinawa_area'), prefectures_path(area_id: 10)
    .col-xs-12
      .prefs
        .prefs__name
          |
          = link_to t('prefectures.index.okinawa'), prefectures_path(pref_id: 47)

app/views/prefectures/_map.html.slim
.area-pick
  ul#imagemap
    li#hokkaido
      = link_to t('prefectures.index.hokkaido_area'), prefectures_path(area_id: 1)
        /a href="hokkaido/hokkaido.html" 北海道
    li#touhoku
      = link_to t('prefectures.index.tohoku_area'), prefectures_path(area_id: 2)
        /a href="tohoku/miyagi" 東北
    li#hokuriku
      = link_to t('prefectures.index.hokuriku_area'), prefectures_path(area_id: 3)
        /a href="hokuriku/nagano.html" 北陸
    li#kanto
      = link_to t('prefectures.index.kanto_area'), prefectures_path(area_id: 4)
        /a href="kanto/tokyo.html" 関東
    li#tokai
      = link_to t('prefectures.index.tokai_area'), prefectures_path(area_id: 5)
        /a href="toukai/shizuoka.html" 東海
    li#kansai
      = link_to t('prefectures.index.kinki_area'), prefectures_path(area_id: 6)
        /a href="kansai/osaka.html" 関西
    li#chugoku
      = link_to t('prefectures.index.chugoku_area'), prefectures_path(area_id: 7)
        /a href="chugoku/hiroshima.html" 中国
    li#shikoku
      = link_to t('prefectures.index.shikoku_area'), prefectures_path(area_id: 8)
        /a href="shikoku/kochi.html" 四国
    li#kyushu
      = link_to t('prefectures.index.kyushu_area'), prefectures_path(area_id: 9)
        /a href="kyushu/fukuoka.html" 九州
    li#okinawa
      = link_to t('prefectures.index.okinawa_area'), prefectures_path(area_id: 10)
        /a href="okinawa/okinawa.html" 沖縄

app/views/prefectures/index.html.slim
.pref-page-bg
  .row
    .col-xs-12.text-center
      h1
        = t('prefectures.index.pagetitle')
      p
        = t('prefectures.index.description')
    .col-xs-12.text-center
      p
        span style="color:#888;"
          = t('app.link.both')
        |  / 
        = link_to t('app.link.budget'), budget_path
        |  / 
        = link_to t('app.link.genre'), genres_path
        |  / 
        = link_to t('app.link.age'), age_path
        |  / 
        = link_to t('app.link.nation'), nation_path
        |  / 
    .col-xs-7
      .prefs__map-bg
        = render 'map'

    .col-xs-5
      = render 'area_list'

.pref-page-bg
  .row
    .album-index
      .album-index__title.text-center
        h2
          = t('.post_index')
        .col-xs-12
          - if @posts.present?
            - @posts.each do |post|
              = render 'posts/post', post: post
            .col-xs-12.text-center
              = paginate @posts
          - else
            h3.bg-danger.text-center
              = t('app.common.no_post')